### ISSUE TITLE
Load Balancer Service created thru Dashboard for Jaeger instance vanishes

### ISSUE THREAD

**Issue by sundar-cs** [jaegertracing/jaeger-operator#1152]
This is on a basic KOPS cluster (with aws as the backend). Same behavior is observed on EKS too.

(1)
Create Jaeger Operator as per:
https://github.com/jaegertracing/jaeger-operator

(2)
Create Jaeger Instance thru "simplest.yaml" as described in above link

(3)
Change "type: ClusterIP" to "type: LoadBalancer" for "simplest-query" service thru Kubernetes Dashboard and verify that it's accessible thru the Browser and that "kubectl get svc -A" shows the service wiith Load Balancer type.

(4)
Run Google Microservices demo app or HotRod app etc and confirm that Jaeger UI shows the traces.
Continue this for a few hours.

(5)
After a few hours Jaeger Query UI is no longer accessible and "EXTERNAL-IP" in "kubectl get svc -A" output is shown as NONE.

For instance:

_default simplest-query LoadBalancer 100.64.66.23 a43a61be1ff744bee95f66ad5d8b1b0d-436551021.us-west-2.elb.amazonaws.com 16686:31955/TCP   1h_

changes to:

_default 	simplest-query 		ClusterIP 		100.64.66.23 		NONE 		16686/TCP 	7h_

Question:
Is this expected when LoadBalancer is added thru the Kubernetes dashboard ?
Is there a better way to accomplish this ?
The reason for taking this approach is due to these 2 issues which preclude the ability to create a Load Balancer service for Jaeger Query upfront:
https://github.com/jaegertracing/jaeger-operator/issues/801
and
https://github.com/jaegertracing/jaeger-operator/issues/1150
(i.e. alternative way of unwrapping the CRD so as to tweak the YAML to have Load Balancer and then apply, but it generates the same output for any input and so this too is ruled out ?)

Please let me know the right way to achieve this.

**Comment by jpkrohling** [comment]
>  Is this expected when LoadBalancer is added thru the Kubernetes dashboard ?

The operator will reconcile the expected with the observed states for objects that are managed by the operator. Changing a service that was provisioned by the operator will make the operator revert your manual changes once it reconciles again.

>  Is there a better way to accomplish this ?

You can accomplish the same by using a different service name and removing the fields telling the operator that it's responsible for managing the object (owner references and the label `managed-by`, basically). It's recommended to use a different service name so that it won't clash with the service that the operator will attempt to provision.

**Comment by jpkrohling** [comment]
I'm closing, as I believe this has been answered, but feel free to reopen if that's not the case.
