### ISSUE TITLE
Remove KUBERNETES_CONFIG default from e2e tests

### ISSUE THREAD

**Issue by joe-elliott** [jaegertracing/jaeger-operator#1160]
I accidentally deployed some tests to actual infrastructure because the default $KUBERNETES_CONFIG points to a common location for a kube config.  Before I ran the tests I had set the more common $KUBECONFIG variable to point to a local k3d cluster assuming that it would be used.

Was I just being careless? or does it make sense to force the user to set this value before running tests?

https://github.com/jaegertracing/jaeger-operator/blob/master/Makefile#L3

**Comment by jpkrohling** [comment]
> does it make sense to force the user to set this value before running tests?

How about we change `KUBERNETES_CONFIG` to `KUBECONFIG`?  I'm sure there was a reason to name it differently from the standard, but we can at least try.

**Comment by joe-elliott** [comment]
Even though it's convenient to keep it pointed at something my instinct is to always force the user to explicitly set it to avoid surprises.

Having said that it might just be my fault for letting my default shell have access to real infra.  This is not the first time I've made this mistake :).

**Comment by jpkrohling** [comment]
> Even though it's convenient to keep it pointed at something my instinct is to always force the user to explicitly set it to avoid surprises.

Guess what will be the first thing I'll do when we require users to always set an env var in order to run the tests :-)

```bash
echo "export KUBERNETES_CONFIG=~/.kube/config" >> ~/.bashrc
```

> Having said that it might just be my fault for letting my default shell have access to real infra

No, I think you are not the first, and I'm not sure this is a problem that happens only with our operator. Better would be if we could determine whether the target cluster is local or remote. If we assume that `minikube` is being used, we could run `minikube update-context` before, with an env var to bypass this step (for the cases where we are using other platforms and do want to run the tests there).

**Comment by jpkrohling** [comment]
Closing, as I'm not sure we want to handle this at the operator. Feel free to reopen if you disagree.
