### ISSUE TITLE
Add 'w3c' to the injected JAEGER_PROPAGATION environment variable

### ISSUE THREAD

**Issue by chgl** [jaegertracing/jaeger-operator#1191]
In https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/inject/sidecar.go#L308 the default propagation formats are set to `jaeger` and `b3`. Many OpenTelemetry clients have adopted the recent W3C TraceContext as a default propagation format.

It would be great if `w3c` were added to this list by default.

**Comment by jpkrohling** [comment]
Sure, sounds good. Do you know what happens when a propagation format isn't recognized? Would the client typically crash, or will it just ignore? The Java client will not crash, but will log a message: 

https://github.com/jaegertracing/jaeger-client-java/blob/568ab68ec2ac5e9e811b1d0d76f752f3242d45d3/jaeger-core/src/main/java/io/jaegertracing/Configuration.java#L458

**Comment by chgl** [comment]
The 

> Sure, sounds good. Do you know what happens when a propagation format isn't recognized? Would the client typically crash, or will it just ignore? The Java client will not crash, but will log a message:
> 
> https://github.com/jaegertracing/jaeger-client-java/blob/568ab68ec2ac5e9e811b1d0d76f752f3242d45d3/jaeger-core/src/main/java/io/jaegertracing/Configuration.java#L458

The C# client does the same: https://github.com/jaegertracing/jaeger-client-csharp/blob/4e97b9ada2a9b30fdc266482f5841f1e5e161d59/src/Jaeger.Core/Configuration.cs#L477

According to https://www.jaegertracing.io/docs/1.19/client-features/ these are the only clients that can be officially configured via that variable. There's definitely still a potential risk, however as the documentation states that `w3c` can be used as a value and should therefore be expected I think we should be ok.

**Comment by jpkrohling** [comment]
Go ahead then :-)
