### ISSUE TITLE
Operator 1.17.7 on OpenShift - wrong jaeger collector service name

### ISSUE THREAD

**Issue by dimovelev** [jaegertracing/jaeger-operator#1317]
We annotate our pods so that sidecars are automatically injected. However, the sidecar created next to our application gets wrong parameters pointing to the collector service in a **different** namespace. The parameter I am talking about is:
`--reporter.grpc.host-port=dns:///jaeger-logsmon-collector-headless.XXX.svc:14250
`

The namespace (XXX in the example above) seems to be the first namespace that we have. In each namespace we create a Jaeger resource with the same name and annotate the pods with that same name. 

I could not find any way to configure this and I assume that this is a bug.

**Comment by jpkrohling** [comment]
I've got a few questions:

1. what are the versions of the components involved? (kubernetes, operator)
1. when you created your application, did you have only one Jaeger instance in your cluster (`jaeger-logsmon` in `XXX`)? Or did you already have another Jaeger instance in the same namespace as your workload?
1. what are the values for the `sidecar.jaegertracing.io` labels and annotations in the pod/deployment?
1. are you able to consistently reproduce it on minikube? If so, please share the steps. Also, please include the debug logs, so that we can see what happened during the sidecar injection.

cc @rubenvp8510

**Comment by dimovelev** [comment]
1. sorry, my bad. this should also be part of the description
2. as far as I understood, yes, we only had (and still have) one jaeger called jaeger-logsmon in the namespace. We might have recreated it a few times in the hope that it would fix the issue.
3. The annotations on the deployment level are:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-logsmon
```
4. Unfortunately we do not use minikube/minishift or any other local openshift / kubernetes environment

Just in case all arguments of the jaeger sidecar container where it is visible how it mixes up two namespaces:
```
      args:
        - >-
          --jaeger.tags=cluster=undefined,deployment.name=XXX-mts,pod.namespace=XXX,pod.name=${POD_NAME:},host.ip=${HOST_IP:},container.name=mts
        - >-
          --reporter.grpc.host-port=dns:///jaeger-logsmon-collector-headless.ZZZ.svc:14250
        - >-
          --reporter.grpc.tls.ca=/etc/pki/ca-trust/source/service-ca/service-ca.crt
        - '--reporter.grpc.tls.enabled=true'
        - '--reporter.type=grpc'
```
ZZZ should have been XXX for it to work correctly.

**Comment by jpkrohling** [comment]
We'll need the debug logs, to understand what's going on there. If you do have a `jaeger-logsmon` instance in the `ZZZ` namespace *and* in the `XXX` namespace, it might indeed be a bug. If you only have one in the `ZZZ` namespace, it seems correct to me. You can check it by issuing a `kubectl get jaegers --all-namespaces`.

**Comment by maxshel** [comment]
This is how it looks like:
```java
AAA    jaeger-logsmon   Running   1.17.6    production   elasticsearch   35d
BBB    jaeger-logsmon   Running   1.17.6    production   elasticsearch   35d
CCC    jaeger-logsmon   Running   1.17.6    production   elasticsearch   35d
XXX   jaeger-logsmon   Running   1.17.7    production   elasticsearch   3d8h
ZZZ    jaeger-logsmon   Running   1.17.6    production   elasticsearch   12d
```
all sidecards got injected with a --reporter.grpc.host-port property which points to the first jaeger instance from this list, independent from namespace.

**Comment by jpkrohling** [comment]
It all makes sense now. You should also have a label in your deployment stating which Jaeger instance got injected, and I think it's qualified with the namespace. In any case, I'm not sure this is a case we tested before.

cc @rubenvp8510

**Comment by objectiser** [comment]
@dimovelev Are you able to upgrade to a newer version? Testing with 1.20 on OCP, with `sidecar.jaegertracing.io/inject: true` (rather than using the jaeger instance name) seems to work.

**Comment by leRobbe** [comment]
I just encountered the same issue..took me days to figure out why the agent just couldn't connect to my collector (I'm new to openshift, jaeger etc.)

I'm using the configuration `sidecar.jaegertracing.io/inject: true` to auto-inject sidecars into my clients (residing in the same namespace as my jaeger deployment - operator version 1.20.4) and had the issue that the agent was there but no traces were showing up. Local testing showed that tracing indeed works. Upon checking the agent logs I discovered that it was trying to connect to a collector with a different IP than the one in my namespace and resulting i/o timeout error.
After asking several colleagues we saw that the jaeger injecting the sidecar is in fact not the one in my namespace but a deployment in a different namespace that I don't have access to.

I'm assuming I'll have to either try to manually inject the sidecars (which I wanted to avoid due to possible version conflicts if the ooperator were updated) or to bypass the agent in the first place and send to the collector directly?
With the latter approach, what possible downsides am I facing? This is not quite clear to me yet as I only saw "sidecar injection recommended" but not why in docs/various blogs etc.

**Comment by jpkrohling** [comment]
@jkandasa, @rubenvp8510, could you please try to reproduce this?

**Comment by leRobbe** [comment]
as per comment in #1414 I was able to solve my issue by instead of `true` using the jaeger instance name in the annotation:
`sidecar.jaegertracing.io/inject: jaeger-name`

guess I was lucky that the jaeger instance in the other namespace is named differently, otherwise my guess is that I'd have the same issue as with `true` parameter
