### ISSUE TITLE
Apply changes to deployed jaeger instance (cr)

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#134]
How to apply changes to deployed jaeger instance? For instance scale up collectors.

How it should be done? Scaling up collectors via kubectl or edit jaeger instance e.g. `kubectl edit jaeger simplest`?  When I edit jaeger instance - `collector.size` nothing happens.

**Comment by jpkrohling** [comment]
Right now, we don't support it. The plan is to support a `size` property within the `JaegerCollectorSpec`, which will scale up/down, detected in the reconciliation routine. I haven't implemented this yet because we might also want to automatically scale based on the metrics, like dropped spans, queue size vs. max queue size, ...

Here's how it would work in practice, following an example from the operator SDK:

https://github.com/operator-framework/operator-sdk-samples/blob/3af4c87e85bda3a0406f557ce32adda454408b75/memcached-operator/pkg/controller/memcached/memcached_controller.go#L123-L134

**Comment by zerda** [comment]
Here is another scenario. I'm applying changes about storage options like 'es.num-replicas=0', currently I have to delete old deployment manually, then the operator will create a new one with the latest options.

I agree with @pavolloffay , it would nice to be documented.

**Comment by jpkrohling** [comment]
Did I understand it correctly that you did manage to update your existing installation? If so, would you be willing to draft something? *Right now*, we do not support updating, but it should change soon and the only way to get the underlying components updated is to indeed update the CR and remove the component that should be updated (or the other way around, I'd have to try).

**Comment by objectiser** [comment]
Some general thoughts:
* If only component `size` properties are changed, then just scale up/down as necessary
* If any other configuration is changed, then add a new deployment of each component, monitor their metrics for a predefined period, and if seems to work ok scale up the new deployment for each component and scale down the old. If problems detected, then scale down and remove the new deployments. This would work on the basis that the existing deployed `Service` objects would load balance across the old and new pods - so the `Service` objects wouldn't ever be touched.
* If strategy changes, then generally I think the approach above would still work as long as there was no requirement for a `Service` object on the ingester - so the service objects would remain the same, just a slight change in the config of the pods - which would be handled in the transition.

The problem area is the agents - whether sidecar or daemonset. Sidecar agent could just be updated with the lifecycle of the associated app - but daemonset is more problematic. We can't start a second overlapping agent on the same node, I don't think updating config in situ would be a good idea, as this could get very complicated regarding compatible versions of the config vs agent image.

**Comment by jpkrohling** [comment]
I think you nailed it. We could classify the changes into three main categories:

- Migration (all-in-one <-> production <-> streaming)
- Configuration updates (like, changing a backing storage password or CLI option)
- Scaling (size changes)

We could detect them in the order above, so:

1. Perform migration steps if needed, and return (assuming the size and config options on the new components will use the new values, in case there are any changes)
1. If no migration is needed, then evaluate if configuration updates are required and do as you outlined before. 
1. If no changes are needed but the size of the deployment isn't correct, then scale up/down as necessary

This could all live in a new package, `pkg/update`.

**Comment by jpkrohling** [comment]
Just to record the progress: the logic above won't work for a couple of reasons, but mostly, we currently have the idea of using the Kubernetes client *only* in the controller. And given that the controller can get only the "latest" instance configuration (ie, the one that has just been applied), it's hard to assess what changes are needed at the controller (too many things to compare) and it's not desired to pass down the client, so that each strategy can query the cluster to get the objects they expect to be there.

Instead, the current idea is to get *all* objects that are owned by the instance and compare that list with the expected state. If there are no objects at all, it's a brand new installation and we just create all objects (like it is now). If we get objects owned by the instance, we are dealing with an update. If it's a migration, configuration change or a simple scale up/down is then decided in the strategies themselves. They could then return a struct containing "Update", "Create" and "Delete" lists.

**Comment by jpkrohling** [comment]
> They could then return a struct containing "Update", "Create" and "Delete" lists.

This won't work as well, as we want the Operator to be smarter than that. We want to allow seamless migration as much as possible. For instance, when migrating from all-in-one to production, we want to:

1. Change the all-in-one deployment labels to include something like `state: to-be-replaced`
1. Change the services to direct traffic only to `state: to-be-replaced`
1. Create the production deployments, with a label like `state: new`
1. Wait for the production deployments to be ready
1. Change the services to direct traffic only to `state: new`
1. If the metrics on the new components are sane, remove the all-in-one deployment
1. Remove the `state` from the service label selector 
1. Remove the `state` from the deployments

We can only achieve this with constant/frequent connection to the Kubernetes client, and we do that only at the `controller` package.

So, the solution seems to have code that is not really generic (and might be hard to maintain) at the `controller` package.

**Comment by objectiser** [comment]
In terms of transitioning from old to new, the use of labels may be one approach, but equally we could manage the number of replicas on each to gradually switch over. Not sure what devops staff usually do?

**Comment by jpkrohling** [comment]
Labels would be similar to "blue/green", managing the replicas would be closer to "canary". For now, we'll do a "big bang" update, but we'll have to decide soon on blue/green vs. canary :-)

**Comment by pavolloffay** [comment]
@jpkrohling can this and #42 be closed?

**Comment by jpkrohling** [comment]
Yes for this one, no for #42, as it involves more knowledge about migration between Jaeger versions and possibly an auto-update mechanism.
