### ISSUE TITLE
Disabling TLS in the collector keeps tls=true option

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#1438]
As reported by @kenfinnigan, setting the option `reporter.grpc.tls.enabled` to false on a CR that has it set to true (like in a CR on OpenShift), will cause the option to be set at both true and false.

**Comment by jpkrohling** [comment]
@jkandasa could you add this to the OpenShift tests?

**Comment by kenfinnigan** [comment]
FYI, it also happens with `collector.grpc.tls.enabled`

**Comment by leRobbe** [comment]
I have the same issue.
I'm manually injecting a sidecar agent (auto-injection not possible due to #1317) but now facing the issue that regardless of what I do to disable tls, the operator either instantly overwrites changes to its yaml config or does this:
![grafik](https://user-images.githubusercontent.com/48852681/127500039-7ceef575-74b8-4852-b552-19303ce4efee.png)

Since I'm new to jaeger/openshift I don't know what else I can do..the sidecar agent is not able to connect to the collector, since the TLS certs are missing (and idk how I can get the certs and provide those) and tls can't be disabled

**Comment by jpkrohling** [comment]
The operator shouldn't touch your deployment if you don't have the auto-inject annotation in your deployment. In any case, could you provide the version of the operator you are using, and any other details that can help us reproduce and eventually fix this?

**Comment by jpkrohling** [comment]
Actually, I see that the PR with the fix hasn't been merged yet, so, if this is the same problem, we know how to reproduce it already.

**Comment by leRobbe** [comment]
I'm using operator version 1.20.4, as already mentioned in #1317 
And yes it seems to be the same problem, just wanted to bump this as I wasn't sure whether or not it was still being looked into.

For now since I don't know where to get the "correct" cert for the agent sidecar, I discovered weird behavior in OpenShift (not sure if this is intentional..) that I'm abusing for now..
Basically re-activating auto-injection (and as expected getting injected by the wrong operator), then the volume mounts for the ca certs of the wrong operator are there, when I switch config back to manual injection without any other changes, pod gets restared and agent injected with my manual config, but volume mounts from the wrong operator are still there so it can connect to my own collector.

Not very pretty but getting my application to work for PoC is a quite time-sensitive matter right now.
