### ISSUE TITLE
Configurable version in JaegerSpec

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#166]
Should we provide a simple conf property to specify the version? Note that at the moment we allow overriding images for each individual component.

IIRC  p8s and etcd operators offers this.

**Comment by jpkrohling** [comment]
This should be relatively easy to do: 

- [ ] Add a `Version string` as part of the `JaegerCommonSpec`
- [ ] Change the `normalize()` function to set `jaeger.Spec.Version` to `viper.GetString("jaeger-version")` if it's empty
- [ ] Change all usages of `viper.GetString("jaeger-version")` to get the version from the newly created property `jaeger.Spec.Version`
- [ ] Tests
- [ ] Documentation (probably only a small entry in the readme)

**Comment by jordo1138** [comment]
@pavolloffay I'm looking to do just what you mentioned, override component version to use "latest" tag since I want to test this change from this morning https://github.com/jaegertracing/jaeger/pull/1473
and since the operator version is 1.11.1 it's pulling the images tagged at 1.11 right? this change currently  only in the latest tag, so in part, question on strategy: Production where should override the version for each component like jaeger-collector etc?

**Comment by jpkrohling** [comment]
@jordo1138 You can follow the [`all-in-one-with-options.yaml`](https://github.com/jaegertracing/jaeger-operator/blob/01754a747e6d0302ab23ccc597a74cd9a9290fc0/deploy/examples/all-in-one-with-options.yaml#L8) example as reference. All components (`collector`, `query`, ...) support the `image` property.

**Comment by jpkrohling** [comment]
I'm closing, as we've decided that the Operator will manage the underlying Jaeger version, based on its version (Operator v1.13 == Jaeger v.1.13). When the operator is updated to, say, 1.14, it will take care to bring all managed instances to the same version.
