### ISSUE TITLE
Jaeger cr-metrics removed?

### ISSUE THREAD

**Issue by mjnagel** [jaegertracing/jaeger-operator#1698]
**Describe the bug**
When installing the latest operator version (1.29.1) I'm noticing that:
- The servicemonitor does not seem to be created by default for monitoring the operator metrics
- The cr-metrics port (8686) is no longer added to the service despite still being shown as an option in the `start` command options

Beyond this, when doing an upgrade from 1.28 -> 1.29.1 the old servicemonitor sticks around and results in a down target showing in prometheus since 8686 seems to no longer expose metrics.

Possibly important to note, I am using the helm chart.

**To Reproduce**
1. Install the latest operator on a cluster with a prometheus/monitoring stack (using the helm chart ideally)
2. Check the service and notice that 8686 no longer shows up.
3. Validate that no service monitor is created
4. To follow the issue, install an older version like 1.28 and notice the different behavior - service has 8686 exposed and servicemonitor is autocreated.

**Expected behavior**
I would expect the operator to continue to expose the cr-metrics or at minimum clean up the servicemonitor it created. I was unable to find any release notes or changelog notes about this issue.

Best I could find was https://github.com/jaegertracing/jaeger-operator/pull/1623 which seems to be where 8686 was removed?

Am I missing something different that I should be doing now? Or does the helm chart need some changes? I did also run into https://github.com/jaegertracing/jaeger-operator/issues/1697 but was able to resolve that on my clone of the helm chart.

**Version (please complete the following information):**
 - Jaeger version: 1.29.1
 - Deployment: Kubernetes (with helm)

**Comment by rubenvp8510** [comment]
Hi because we moved to operator-sdk 1.13, We had to migrate the metrics to a new way to do the things. (See https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.0.0/#removed-packages-pkgkube-metrics-and-pkgmetrics) 

I just sent a PR https://github.com/jaegertracing/jaeger-operator/pull/1706 which adds the CR metrics, but now there is no different endpoint for CR metrics. we use the same port for all the metrics.

Also, notice that the exposed metrics changed a little bit. Now the CR metric is a gauge named `resource_created_at_seconds`

This is an example of exposed gauges.
```
# HELP resource_created_at_seconds Timestamp at which a resource was created
# TYPE resource_created_at_seconds gauge
resource_created_at_seconds{group="jaegertracing.io",kind="Jaeger",name="my-jaeger",namespace="default",version="v1"} 1.641884385e+09
```

**Comment by mjnagel** [comment]
Tracking now, thanks @rubenvp8510 !
