### ISSUE TITLE
How to: create Jaeger instance in different namespace to operator

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#24]
One of the benefits of the operator is supposed to be that it can be installed once, and used to create multiple Jaeger instances in different namespaces.

If this is possible, then we should document (possibly just in the readme) how such a configuration would be achieved.

**Comment by mkjoerg** [comment]
This would be very beneficial because the actual deployment model would say one Jaeger Operator per Namespace and if you install by Helm, the installation fails after the second one, because the CRD is already existing.

**Comment by dylanfoster** [comment]
Trying this as well, with the operator in the default namespace, it "creates" the jaeger instance in another namespace but the pods never show up, nor do the agent sidecars

**Comment by jpkrohling** [comment]
@dylanfoster I think this is because the operator watches only a single namespace: 

https://github.com/jaegertracing/jaeger-operator/blob/1e134beeb2409beed78d632b858a6691ed4f9cbf/pkg/cmd/start/main.go#L84

If you are comfortable with Go, could you try removing the `Namespace` part? Like this:

```go
	mgr, err := manager.New(cfg, manager.Options{})
```

According to the manager's documentation, an empty `Namespace` would default to watching all namespaces:

https://github.com/kubernetes-sigs/controller-runtime/blob/0dd6edb02bf23e3669a3edc50ef00a38719173b0/pkg/manager/manager.go#L111-L115
