### ISSUE TITLE
I'm facing the same issue with GKE 1.28 and Jaeger operator helm chart through ArgoCD. In Argo it shows this error message:

### ISSUE THREAD

**Issue by laith-leo** [jaegertracing/jaeger-operator#2515]
I'm facing the same issue with GKE 1.28 and Jaeger operator helm chart through ArgoCD. In Argo it shows this error message:

`Translation failed: invalid ingress spec: service "jaeger/jaeger-sandbox-operator-jaeger-query" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

_Originally posted by @laith-leo in https://github.com/jaegertracing/jaeger-operator/issues/1174#issuecomment-2021371499_

**Comment by kehao95** [comment]
Hi @laith-leo this issue doesn't necessary mean you failed to deploy the Jaeger operator and jaeger deployment. It's just the ingress & service is not proper configured for the ingress-controller so k8s can't expose the service out of the cluster. 

---

So instead of relay on ingress to expose the service, you may try https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/ to access the service instead. 

you can use the following kubectl port-forward command. This will allow you to access the Jaeger UI by visiting http://localhost:16686 on your local machine.

Here's the command:

```
kubectl port-forward svc/simplest-query 16686:16686 -n observability
```
This command does the following:

- **svc/simplest-query**: Specifies the service to which you're forwarding a port.
- **16686:16686**: Forwards your local port 16686 to the service's port 16686.
- **-n observability**: Specifies the namespace where the service is located.

**Comment by laith-leo** [comment]
@kehao95  It is not about how do I expose the service for sure! Also, I don't need to expose it since I'm routing the services' traces internally to Jaeger.  The issue I'm facing is similar to the one in #2515, I have this error message showing in my GitOps tool:

`Translation failed: invalid ingress spec: service "jaeger/jaeger-sandbox-operator-jaeger-query" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

It is not hurting anything, but it is nice to see all the resources in a green state.

**Comment by laith-leo** [comment]
I resolved it by using the controller.
