### ISSUE TITLE
Add liveness probes

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#56]
Add liveness probes and enable the user to optionally specify the initial delay and period durations.

**Comment by amila-ku** [comment]
i would like to work on this if this is still required..

**Comment by jpkrohling** [comment]
Looks like we only have readiness probes:

https://github.com/jaegertracing/jaeger-operator/blob/b6211a465568a11dcfd3b3ecf7ff16b30d8a9915/pkg/deployment/all_in_one.go#L173-L181

So, go ahead!

**Comment by amila-ku** [comment]
thanks for pointing to the file, i will create a PR

**Comment by amila-ku** [comment]
@jpkrohling when going through the implementation noticed the current ReadinessProbe set in config is not configurable by user,i could follow the same approach or change the probes to be configurable by user unless the intention is not to expose the value as user configurable. Since this issue mentions the values has to be configurable i suppose it should be the approach to take. It would be great if you could clarify.

**Comment by objectiser** [comment]
@amila-ku Best to follow the current pattern used by ReadinessProbe, so not configurable - we can always add the configurability later if required, but in general it is better to keep the Jaeger CR as simple as possible.

**Comment by amila-ku** [comment]
thanks for clarifying i will follow the current pattern.

**Comment by amila-ku** [comment]
PR  merged.
