### ISSUE TITLE
Move hard coded strings to constants

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#59]
There are quite a few hard coded strings in the code, like `jaeger-agent` as the container name for the Jaeger Agent sidecar container. They should all move to constants.

Where appropriate, types should be used to represent constant values.

**Comment by AndreaM16** [comment]
Working on this!

**Comment by AndreaM16** [comment]
@jpkrohling what about sharing constants in the same package? For instance, in `pkg/deployment`, strings like ` "jaeger-version"` are used more than once in different files. 

Would you agree on creating a new file called `values.go` in which you define package level shared constants?

Otherwise, how would you handle it?

**Comment by jpkrohling** [comment]
> Would you agree on creating a new file called values.go in which you define package level shared constants?

Yes, I think it's a good approach. Another option would be to have a dedicated package for constants, but I think I prefer to leave the constants closer to where they semantically belong to (jaeger-version belonging to the deployment package).

**Comment by AndreaM16** [comment]
Perfect.
