### ISSUE TITLE
Inject environment information into JAEGER_TAGS env variable

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-operator#632]
The operator could get environment information (e.g. namespace) and inject it into environmental variable `JAEGER_TAGS` which can be used by jaeger agent to add tags to each process/span reporting to the collector.

Related issue https://github.com/jaegertracing/jaeger/issues/1755

**Comment by jpkrohling** [comment]
With the current way we inject the sidecar, the operator can't get the `POD_NAME` where the agent is running, so, it can't build the `JAEGER_TAGS` env var. The reason is that changing the deployment to inject the env var will trigger a new deployment, which will change the pod name.

We have two solutions here:

- [ ] Use the webhook approach from #171 / #473, which will allow the sidecar to be injected before the pod is created, but after it has a name (IIRC)
- [ ] Add all the metadata we want as individual env vars via the downward API and add an `entrypoint.sh` shell script to the agent's image, assembling all those env vars into JAEGER_TAGS.

The first option won't require Kubernetes-specific information to be a concern for the agent, while the second option will require a far smaller change.

cc @objectiser

**Comment by objectiser** [comment]
Until we know whether option 1 is feasible, perhaps work on option 2 - but make the tag name configurable possibly via another env var. So by default tag should be `hostname` to match with the `peer.hostname` tag, and then the operator (as deploying to kubernetes) can change it to be `pod`.

**Comment by jpkrohling** [comment]
> So by default tag should be hostname to match with the peer.hostname tag, and then the operator (as deploying to kubernetes) can change it to be pod.

Sorry, I'm not following. The hostname happens to be the same as the pod name, but we need to change the operator anyway to pass the namespace to the agent, so, we can also just add the pod name as an extra env var as well. The `entrypoint.sh` can then just get the pod name from the env var instead of trying to get the hostname, or not set anything at all if POD_NAME isn't set, as it would be the case when it's a daemon set.

**Comment by objectiser** [comment]
Ok, forgot about namespace - but was trying to avoid using k8s specific terms in the `entrypoint.sh`.

**Comment by jpkrohling** [comment]
Based on your last message, I'm not sure whether I should attempt to get that old PR into a working state, or I should start a discussion about adding Kubernetes-specific bits to the (not yet existing) `entrypoint.sh`. Note that the image is currently a scratch image, and we'd need to change it to use a base OS that is capable of executing shell scripts.

**Comment by objectiser** [comment]
Before deciding on approach, is there a list of tags we are looking to create, and the source of the info in k8s?

**Comment by jpkrohling** [comment]
To correlate with metrics and logs, we need: cluster, namespace, pod name, container. The first isn't currently available, AFAIK, and the last isn't required. Both namespace and name can be obtained via downward API, so, they can be set to an "intermediary" env var in the pod if we use an entrypoint script, or can be used directly in the webhook. The container name can also be set to an env var by the operator, but only after looking into the `Container` object within the `PodSpec`/`Pod`, which is possible in all scenarios (current injection mechanism, entrypoint script, wehook).

**Comment by objectiser** [comment]
Ok thanks - so if using the `entrypoint.sh` approach, we don't necessarily need it to be k8s specifc - can't it use another env var to list the tags that are to be provisioned, along with the env var that will provide the value? Thus making it a platform independent mechanism for the jaeger agent?

**Comment by objectiser** [comment]
Actually - if I recall correctly - no change would be required if the agent works as the java client - Java client takes JAEGER_TAGS="mytag=$(ENV_VAR)" format I believe - so if agent did the same, then no `entrypoint.sh` would be required - it would automatically take the value from the specified env var.

**Comment by objectiser** [comment]
In which case, we might want to inject the values in both the agent and also the app (for the client/tracer) to use - in case it reports directly to the collector.

**Comment by jpkrohling** [comment]
I think there's no harm in adding to both, right?

**Comment by jpkrohling** [comment]
I guess there is harm in adding to both:

![image](https://user-images.githubusercontent.com/13387/64429288-eae45000-d0b5-11e9-89e0-7c1bf56c6711.png)

**Comment by objectiser** [comment]
I guess the other option is to support injection of just environment variables, which then sets up the env var of the collector - so the app doesn't need to do any specific config of env vars?

For example, have `collector.jaegertracing.io/inject`?
