### ISSUE TITLE
Are the requirements ingress and separate authentication/authorization?

### ISSUE THREAD

**Issue by nha** [jaegertracing/jaeger-operator#724]
from the README

```
This will create a Jaeger instance named simplest. The Jaeger UI is served via the Ingress, like:

$ kubectl get ingress
NAME             HOSTS     ADDRESS          PORTS     AGE
simplest-query   *         192.168.122.34   80        3m
In this example, the Jaeger UI is available at http://192.168.122.34.
```

This means the UI would be public to anyone right? And also that you need to have an ingress set up (which may or may not be the case in bare-metal kubernetes clusters)?

Was it the case before? I recall being able to hit `jaegertracing-collector:14268/api/traces` and  `jaegertracing-collector:5788` service before - can this still be done?

**Comment by jpkrohling** [comment]
Correct, the ingress is so that the Jaeger *UI* is accessible via an external IP, which might be still be internal to your internal network (which is the case with `minikube`). That's one of the main reasons why we allow disabling the ingress, as the rules differ from setup to setup and it's easier to manage the ingress externally to the operator.

Note that the ingress isn't exposing the collector.

And you don't need an ingress for in-cluster communication: if your application is deployed within the same Kubernetes cluster, should should still be able to connect to the collector via the service (`jaegertracing-collector:14268` that you mentioned).

**Comment by nha** [comment]
Got it thanks 👍
