### ISSUE TITLE
is clusterrole required for Jaeger operator?

### ISSUE THREAD

**Issue by christine-gong** [jaegertracing/jaeger-operator#791]
Hi,
I am wondering if clusterrole and clusterrolebinding are required for jaeger operator  to function properly in kubernetes. (e.g. https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/role.yaml and https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/role_binding.yaml) 

Since everything is living under `tracing` namespace, i think role and rolebinding would be good enough.  We do not want to open cluster permission when it's unnecessary

After changing to Role and RoleBinding, my operator throws the following errors when applying jaeger components yamls.
```
1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tracing:jaeger-operator" cannot list resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

**Comment by jpkrohling** [comment]
Cluster permissions (role/role binding) should be required only when watching all namespaces. In all other cases, the operator has to be able to work without cluster permissions.

It should be possible to fix the code so that the operator won't break if it can't list cluster roles/role bindings. A quick workaround should be to not return an error on this code:

https://github.com/jaegertracing/jaeger-operator/blob/8eb82f0caad364914ea6f353fa46b180d5ee2b21/pkg/controller/jaeger/jaeger_controller.go#L266-L268

Ideally, though, the operator would attempt to get a list of cluster role bindings and set a new configuration entry via viper, stating whether or not it has the permission to get a list of cluster role bindings. Then, the following code should check this new config entry before attempting to list the cluster role bindings:

https://github.com/jaegertracing/jaeger-operator/blob/8eb82f0caad364914ea6f353fa46b180d5ee2b21/pkg/controller/jaeger/clusterrolebinding.go#L16-L62

Would you be willing to give it a try?

**Comment by christine-gong** [comment]
@jpkrohling thanks! sure, i will try to fix it.
