### ISSUE TITLE
Add support for image pull secrets

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-operator#80]
Enable the CR to specify a list of image pull secrets that could be used with any deployments, or possibly a serviceaccount if we define one.

**Comment by jpkrohling** [comment]
How does this look like in a YAML file?

**Comment by objectiser** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by jpkrohling** [comment]
Thanks! I think this should be done in a similar way as #76: one option at the top-level `JaegerSpec`, with possible overrides from specific-specs (`JaegerAgentSpec`, `JaegerCollectorSpec`, ...)

**Comment by objectiser** [comment]
Other option is image pull secrets can be specified on a service account: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#service-account-admission-controller

Not sure if we want to (provide option for) a jaeger service account?

**Comment by jpkrohling** [comment]
Good question. I think a service account per instance will be inevitable, but it would be good to add it only once we have a real requirement.

**Comment by objectiser** [comment]
Possibly - although this may be a good requirement to justify it - as the pull secret could just be associated with the service account I believe.

**Comment by jpkrohling** [comment]
Agree. Another question: what if the pod has two containers, each from a different private repository, thus requiring different secrets? I think this is an edge case that we don't need to really worry about it now, but would be nice to at least understand what would happen.

Another question: do we want one secret per component, so that `jaeger-agent` can be on a private repo but `jaeger-collector` not?

**Comment by objectiser** [comment]
Using istio's tracing helm chart as an example, I believe it is possible to list[ multiple secrets](https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/tracing/values.yaml#L38-L42) so I guess the appropriate secret will be used in the relevant context?

It is also possible to list zero or more hosts - which can be used when setting up the ingress config - not sure if we also need to support that:  https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/tracing/templates/ingress.yaml#L19-L32

**Comment by jungopro** [comment]
Hi @jpkrohling, I'm trying to implement `kind: jaeger` with the serviceAccount spec and having issues.

My scenario:

- `jaeger-operator` is deployed in `jaeger` namespace with `WATCH_NAMESPACE=""`
- jaeger instance (`kind: jaeger`) deployed in a different namespace (`application`) as part of an application we develop.

The operator notify that it can't create a service account since it already exists, which is true (as part of the `application` deployment I deploy my own service account with attached `secrets` and `imagePullSecrets` that I want the `kind: jaeger` to use)

My question is: **how can I define for `kind: jaeger` to use an existing service account instead of trying to create a new one?**

_more info_

I'm in an air-gapped site and can't provide a full yaml example, but in a nutshell:

- I have a helm chart that deploys both the `kind: jaeger` and the `application` service account
- I'm using Jaeger components v1.12 (operator, collector, query, etc...)
- I get that there is a name conflict between the **already existing** service account and the **name** of the `kind: jaeger`, but I actually want them to have the same name

```bash
$ kubectl describe jaeger -n application

Name: application
Namespace: application
API Version: jaegertracing.io/vq
Kind: Jaeger
...
Spec:
  Service Account: application

$ kubectl describe serviceaccount application

Name: application
Namespace: application
...
Image pull secrets: dockerregistrylogin
```

**Comment by jpkrohling** [comment]
@jungopro, is your previous comment in the same context as #499? Would adding support for overriding the image pull secret be sufficient to cover this case?

**Comment by jungopro** [comment]
@jpkrohling yes, it will
either using custom serviceaccount for the es part of the yaml of a custom image pull secret will do
much appreciated

**Comment by jpkrohling** [comment]
Most of the Jaeger parts already have support for a custom service account, but we do not control the ES part, as it's defined by the [ES operator's CRD](https://github.com/openshift/elasticsearch-operator/blob/master/pkg/apis/logging/v1/elasticsearch_types.go#L10).

I'll let @pavolloffay comment on that, as he might know if there's a workaround. It might take a few days, as he's off this week.

**Comment by jpkrohling** [comment]
We just merged a change that allows a ServiceAccount to have its ImagePullSecrets customized after it's been created by the Jaeger Operator. I believe this would cover all the cases listed in this PR, except for the Elasticsearch one (by @jungopro) as it's outside of this operator's scope.

I'm closing this, but we'll reopen if we think that we need a more appropriate support for defining image pull secrets as part of the CR.
